In [8]:
import numpy as np

In [10]:
np.triu_indices(67,2)

(array([ 0,  0,  0, ..., 63, 63, 64], dtype=int64),
 array([ 2,  3,  4, ..., 65, 66, 66], dtype=int64))

In [27]:
n=5
a=np.arange(n*(n+1)//2)
b=np.arange(n*(n-1)//2)

In [28]:
c=np.zeros((n,n))
c[np.triu_indices(n)]=a
c[np.tril_indices(n,-1)]=b

In [19]:
a[2]=14
a

array([ 0,  1, 14,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
c

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  5.,  6.,  7.,  8.],
       [ 1.,  2.,  9., 10., 11.],
       [ 3.,  4.,  5., 12., 13.],
       [ 6.,  7.,  8.,  9., 14.]])

In [1]:
%run main.py --dataset=WN18RR --num_iterations=100 --batch_size=128 --lr=0.003 --dr=1.0 --edim=200 --rdim=30 --input_dropout=0.2 --hidden_dropout1=0.2 --hidden_dropout2=0.3 --label_smoothing=0.1 --bk=False

False
Removing the redundant symmetric relations in the training set...
Training the TuckER model...
Number of training data points: 70323


Exception in thread Thread-30:
Traceback (most recent call last):
  File "C:\Users\joss1\.conda\envs\torch\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\joss1\.conda\envs\torch\lib\site-packages\wandb\file_pusher.py", line 85, in run
    self.cleanup_file()
  File "C:\Users\joss1\.conda\envs\torch\lib\site-packages\wandb\file_pusher.py", line 76, in cleanup_file
    os.remove(self.save_path)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\joss1\\AppData\\Local\\Temp\\tmpc4soc6iewandb\\requirements.txt'

Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\Users\joss1\.conda\envs\torch\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\joss1\.conda\envs\torch\lib\site-packages\wandb\file_pusher.py", line 85, in run
    self.cleanup_file()
  File "C:\Users\joss1\.conda\envs\torch\lib\site-packages\wandb\file_pus

Starting training...
Iteration:1
Training Time:23.2195086479187
Loss:0.08482538237822829
Validation:
Number of data points: 3034
Hits @10: 0.0
Hits @3: 0.0
Hits @1: 0.0
Mean rank: 18835.90145023072
Mean reciprocal rank: 0.00022916584880699616
Iteration:2
Training Time:21.13247013092041
Loss:0.00444368820926347
Validation:
Number of data points: 3034
Hits @10: 0.0003295978905735003
Hits @3: 0.0
Hits @1: 0.0
Mean rank: 18029.882003955176
Mean reciprocal rank: 0.0002770284946330836
Iteration:3
Training Time:20.80135750770569
Loss:0.0018801935474146848
Validation:
Number of data points: 3034
Hits @10: 0.0006591957811470006
Hits @3: 0.0
Hits @1: 0.0
Mean rank: 17430.509887936718
Mean reciprocal rank: 0.00035881752086820885
Iteration:4
Training Time:21.125490188598633
Loss:0.0012432180455006245
Validation:
Number of data points: 3034
Hits @10: 0.0013183915622940012
Hits @3: 0.0006591957811470006
Hits @1: 0.0003295978905735003
Mean rank: 16925.255108767306
Mean reciprocal rank: 0.000908962936

Number of data points: 3034
Hits @10: 0.07976268951878708
Hits @3: 0.05471324983520105
Hits @1: 0.04054054054054054
Mean rank: 14830.343111404087
Mean reciprocal rank: 0.053455763114989126
Iteration:32
Training Time:21.07858395576477
Loss:0.0004118984760242273
Validation:
Number of data points: 3034
Hits @10: 0.08734344100197759
Hits @3: 0.06624917600527357
Hits @1: 0.04515491100856955
Mean rank: 14824.376400791034
Mean reciprocal rank: 0.06005260730089773
Iteration:33
Training Time:21.151420831680298
Loss:0.00040862085498466277
Validation:
Number of data points: 3034
Hits @10: 0.08635464733025709
Hits @3: 0.06196440342781806
Hits @1: 0.04515491100856955
Mean rank: 14929.404087013843
Mean reciprocal rank: 0.059205170440370276
Iteration:34
Training Time:21.122498989105225
Loss:0.00040348223828240643
Validation:
Number of data points: 3034
Hits @10: 0.08701384311140409
Hits @3: 0.06987475280158208
Hits @1: 0.04779169413315755
Mean rank: 14873.232036914964
Mean reciprocal rank: 0.06292525

Hits @10: 0.14304548450889915
Hits @3: 0.11667765326301911
Hits @1: 0.08734344100197759
Mean rank: 15562.977916941332
Mean reciprocal rank: 0.10814232400183128
Iteration:62
Training Time:20.953949451446533
Loss:0.00035915226214489884
Validation:
Number of data points: 3034
Hits @10: 0.14007910349373764
Hits @3: 0.11997363216875412
Hits @1: 0.0912986156888596
Mean rank: 15457.674686882005
Mean reciprocal rank: 0.11040325712881636
Iteration:63
Training Time:21.331937551498413
Loss:0.00035962907053612136
Validation:
Number of data points: 3034
Hits @10: 0.14205669083717865
Hits @3: 0.12129202373104812
Hits @1: 0.08965062623599208
Mean rank: 15484.17798286091
Mean reciprocal rank: 0.10998760978482426
Iteration:64
Training Time:21.225224018096924
Loss:0.000358683545359613
Validation:
Number of data points: 3034
Hits @10: 0.14667106130520766
Hits @3: 0.12162162162162163
Hits @1: 0.09294660514172709
Mean rank: 15648.01713909031
Mean reciprocal rank: 0.11250742882096791
Iteration:65
Training T

Iteration:92
Training Time:21.141447067260742
Loss:0.000350450431748565
Validation:
Number of data points: 3034
Hits @10: 0.16183256427158865
Hits @3: 0.13744232036914963
Hits @1: 0.1064601186552406
Mean rank: 15138.70072511536
Mean reciprocal rank: 0.12768399483331358
Iteration:93
Training Time:20.98087787628174
Loss:0.0003504231836915197
Validation:
Number of data points: 3034
Hits @10: 0.16710613052076467
Hits @3: 0.13974950560316415
Hits @1: 0.1034937376400791
Mean rank: 15300.08009228741
Mean reciprocal rank: 0.12705373714175514
Iteration:94
Training Time:20.94696879386902
Loss:0.0003501384648256202
Validation:
Number of data points: 3034
Hits @10: 0.16545814106789716
Hits @3: 0.14040870138431114
Hits @1: 0.10909690177982861
Mean rank: 15018.043177323665
Mean reciprocal rank: 0.13109833357923725
Iteration:95
Training Time:20.9439754486084
Loss:0.00034990875954261154
Validation:
Number of data points: 3034
Hits @10: 0.16908371786420567
Hits @3: 0.14271588661832565
Hits @1: 0.109096

In [ ]:
type(model)

In [ ]:
args.bk

In [ ]:
import wandb
wandb.login('1e505430989c86455d2d70e1ef990b4bc50cb69c')
from load_data import Data
import numpy as np
import torch
import time
from collections import defaultdict
from model import *
# from model_sym import *
from torch.optim.lr_scheduler import ExponentialLR
import argparse
import os

In [ ]:
dataset = "WN18RR"
data_dir = "data/%s/" % dataset
d = Data(data_dir=data_dir, reverse=False)
kwargs = {"input_dropout": 0.2, "hidden_dropout1": 0.2,
                       "hidden_dropout2": 0.3, "bk": False}

In [ ]:
model = TuckER(d,200,30,**kwargs)
state = wandb.restore('model_state.pth',run_path='rkbrary/ift6760-exp/1wtu4v7p') #rkbrary/ift6760-exp/1wtu4v7p
checkpoint = torch.load(state.name)
# checkpoint=torch.load('wandb/run-20200413_055149-ihc8l1ta/model_state_new.pth')
model.load_state_dict(checkpoint['model_state_dict'])

In [ ]:
# state.name

In [ ]:
W=experiment.model.W.data.to('cpu')
R=experiment.model.R.weight.data.to('cpu')

In [ ]:
W_r=torch.einsum('ijk,ni->njk',W,R)
constraints=torch.tensor([0,1,-1,0,-1,-1,-1,-1,1,0,1])

In [ ]:
for i in range(len(W_r)):
    print(torch.norm(W_r[i]+W_r[i].t()),torch.norm(W_r[i]-W_r[i].t()), constraints[i], d.relations[i])

In [ ]:
# E=model.E.weight.data

In [ ]:
model.cuda()
model.eval()

In [ ]:
hits = []
ranks = []
for i in range(10):
    hits.append([])
true_rel=np.zeros(len(d.relations))
false_rel=np.zeros(len(d.relations))
entity_idxs = {d.entities[i]:i for i in range(len(d.entities))}
relation_idxs = {d.relations[i]:i for i in range(len(d.relations))}
def get_data_idxs(data):
    data_idxs = [(entity_idxs[data[i][0]], relation_idxs[data[i][1]], \
                  entity_idxs[data[i][2]]) for i in range(len(data))]
    return data_idxs

def get_er_vocab(data):
    er_vocab = defaultdict(list)
    for triple in data:
        er_vocab[(triple[0], triple[1])].append(triple[2])  # may contain multiple connections (exemple hyponym)
    return er_vocab

def get_batch(er_vocab, er_vocab_pairs, idx):
    batch = er_vocab_pairs[idx:idx+128]
    targets = np.zeros((len(batch), len(d.entities)))
    for idx, pair in enumerate(batch):
        targets[idx, er_vocab[pair]] = 1.
    targets = torch.FloatTensor(targets)
    return np.array(batch), targets

test_data_idxs = get_data_idxs(d.test_data)
er_vocab = get_er_vocab(get_data_idxs(d.data))

for i in range(0, len(test_data_idxs), 128):
    data_batch, _ = get_batch(er_vocab, test_data_idxs, i)
    e1_idx = torch.tensor(data_batch[:,0]).type(torch.LongTensor).cuda()
    r_idx = torch.tensor(data_batch[:,1]).type(torch.LongTensor).cuda()
    e2_idx = torch.tensor(data_batch[:,2])
    predictions = experiment.model.forward(e1_idx, r_idx)
    
            
    for j in range(data_batch.shape[0]):
        filt = er_vocab[(data_batch[j][0], data_batch[j][1])]
        if len(filt)>1:print(r_idx[j],len(filt))
        target_value = predictions[j,e2_idx[j]].item()
        predictions[j, filt] = 0.0
        predictions[j, e2_idx[j]] = target_value
    
    pred_idx = torch.argmax(predictions, dim=1).to('cpu')
    for i in range(len(pred_idx)):
        if (pred_idx[i]==e2_idx[i]): true_rel[r_idx[i]]+=1
        else: false_rel[r_idx[i]]+=1

    sort_values, sort_idxs = torch.sort(predictions, dim=1, descending=True)

    sort_idxs = sort_idxs.cpu().numpy()
    for j in range(data_batch.shape[0]):
        rank = np.where(sort_idxs[j]==e2_idx[j].item())[0][0]
        ranks.append(rank+1)

        for hits_level in range(10):
            if rank <= hits_level:
                hits[hits_level].append(1.0)
            else:
                hits[hits_level].append(0.0)

In [ ]:
d.relations

In [ ]:
np.mean(hits[0])

In [ ]:
constraints=[0,1,-1,0,-1,-1,-1,-1,1,0,1]
d.relations
sym=[]
for i in constraints:
    if i==0: sym.append('any')
    elif i==1: sym.append('symmetric')
    else: sym.append('antisymmetric')

In [ ]:
import pandas as pd
df=pd.DataFrame(data=[sym,true_rel,false_rel,true_rel+false_rel,true_rel/(true_rel+false_rel),false_rel/(true_rel+false_rel)],index=['Property','Pos','Neg','Total','Pos_Rate','Neg_Rate'],columns=d.relations)
df

In [ ]:
true_rel

In [ ]:
false_rel

In [ ]:
false_rel+true_rel

In [ ]:
true_rel/(true_rel+false_rel)

In [ ]:
false_rel/(true_rel+false_rel)

In [ ]:
sum(true_rel+false_rel)

In [ ]:
score=[]
for e in E:
    score=torch.sigmoid(torch.einsum('j,ijk,lk->il',e,W_r,E))
    score.size()

In [ ]:
experiment.retrain(2, 'rkbrary/ift6760-exp/ihc8l1ta', 'model_state_new.pth')

In [ ]:
get_data_idxs(d.test_data)

In [ ]:
experiment.get_data_idxs(d.test_data)